env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
  - react
  - '@typescript-eslint'
rules:
  camelcase: 'error'
  consistent-this: ['error', 'that']
  curly: 'error'
  default-case: 'error'
  default-case-last: 'error'
  dot-notation: 'error'
  eqeqeq: 'error'
  guard-for-in: 'error'
  no-alert: 'error'
  no-caller: 'error'
  no-console: 'error'
  no-else-return: 'error'
  no-use-before-define: 'error'
  no-var: 'error'
  object-shorthand: 'error'
  prefer-const: 'error'
  prefer-template: 'error'
  prettier/prettier: 'error'
  radix: 'error'
  react/jsx-fragments: 'error'
  react/jsx-no-useless-fragment: 'error'
  react/jsx-sort-props: ['error', { ignoreCase: true }]
  react/self-closing-comp: ['error', { html: false }]
  sort-imports: ['error', { ignoreCase: true, ignoreDeclarationSort: true }]
  '@typescript-eslint/no-shadow': 'error'
settings:
  react:
    version: detect
